---
title: "Data Tidying"
author: "Ben"
date: "October 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(DT)
```

Read in catch data from [Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.](https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1)

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

`select` (looks like code but doesn't run as code) the columns needed for analysis

```{r}
catch_clean <- catch_df %>%
  select(-All, -notesRegCode)
head(catch_clean)
```

Change from wide to long format using `gather`

```{r}
catch_long <- gather(catch_clean, key = "species", value = "catch", -Region, -Year)
head(catch_long)
```


```{r}
catch_clean <- catch_df %>% 
  #select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
  select(-All, -notesRegCode) %>% 
  gather(key = "species", value = "catch", -Region, -Year) %>% 
  rename(catch_thousands = catch)
tail(catch_clean)

```

```{r}
test <-as.numeric(catch_clean$catch_thousands)
index <- which(is.na(test))
head(test)
index
catch_clean[index, ] 
```

```{r}
catch_clean_mutated <- catch_clean %>%
  #change erroneous "I" in dataframe to "1"
  mutate(catch = ifelse(catch_thousands == "I", 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.numeric(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000) %>% 
  select(-catch_thousands)
  

tail(catch_clean_mutated)
```
split using `group by`
apply and combine using `summarize`

```{r}
catch_summarized <- catch_clean_mutated %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch))

head(catch_summarized)

```

```{r}
catch_summarized <- catch_clean_mutated %>% 
  group_by(Region, species) %>% 
  summarize(mean_catch = mean(catch), n_obs = n())

print(catch_summarized)

```



```{r}
catch_chinook <- catch_clean_mutated %>% 
  filter(species == "Chinook") %>% 
  arrange(-catch)

head(catch_chinook)
```


Join with metadata table

```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"), stringsAsFactors = FALSE)# %>% 
  #rename(Region = code)
#left_join(catch_df, region_defs, by = "Region")
region_defs <- region_defs %>% 
  select(code, mgmtArea)
```


```{r}
catch_joined <- left_join(catch_clean_mutated, region_defs, by = c("Region" = "code"))
tail(catch_joined)

#Check merge for NA generation
i <- is.na(catch_joined)

```
New topic

```{r}

dates_df <- data.frame(date = c("5/24/1930",
                                "5/25/1930",
                                "5/26/1930",
                                "5/27/1930",
                                "5/28/1930"),
                       stringsAsFactors = FALSE)

dates_df %>% 
  separate(date, c("month", "day", "year"), "/")

```

```{r}
dates_seperate <-dates_df %>%
  separate(date, c("month", "day", "year"), "/") %>% 
  unite(col = date_iso, year, month, day, sep = "-")
dates_seperate
```

Still needs leading zeros


